'use strict';class JuliaSetParams{constructor(){this.realComponent=$("#realComponent").val();this.imaginaryComponent=$("#imaginaryComponent").val();this.minXValue=$("#minXValue").val();this.maxXValue=$("#maxXValue").val();this.minYValue=$("#minYValue").val();this.maxYValue=$("#maxYValue").val();this.pictureWidth=$("#pictureWidth").val();this.pictureHeight=$("#pictureHeight").val();this.iterations=$("#iterations").val();this.maxModulus=$("#maxModulus").val()}equals(a){return a&&a instanceof JuliaSetParams&&
this.realComponent==a.realComponent&&this.imaginaryComponent==a.imaginaryComponent&&this.minXValue==a.minXValue&&this.maxXValue==a.maxXValue&&this.minYValue==a.minYValue&&this.maxYValue==a.maxYValue&&this.pictureWidth==a.pictureWidth&&this.pictureHeight==a.pictureHeight&&this.iterations==a.iterations&&this.maxModulus==a.maxModulus}}
class JuliaSetConstraints{constructor(a){a=JSON.parse(a);this.sqlIntMin=a.sqlIntMin;this.sqlIntMax=a.sqlIntMax;this.sqlDecLength=a.sqlDecLength;this.sqlDecPrecision=a.sqlDecPrecision;this.maxDecIntDigits=this.sqlDecLength-this.sqlDecPrecision+1;this.sqlDecMax=parseFloat("1e"+this.maxDecIntDigits);this.sqlDecMin=-this.sqlDecMax;this.iterationsLimit=a.iterationsLimit;this.modulusLimit=a.modulusLimit;this.resolutionLimit=a.resolutionLimit;$("#iterations").attr("max",this.iterationsLimit);$("#maxModulus").attr("max",
this.modulusLimit);$("#pictureWidth").attr("max",this.resolutionLimit);$("#pictureHeight").attr("max",this.resolutionLimit)}isValidDecimal(a){var b=$(a);a=b.find(".form-control");b=b.find(".invalid-feedback");if(!this.validDecimal(a.val()))return a.addClass("is-invalid"),b.text("Please enter a number between -10^"+this.maxDecIntDigits+" and 10^"+this.maxDecIntDigits+" (exclusive)."),$("html, body").scrollTop(a.closest(".row").offset().top),!1;a.removeClass("is-invalid");b.text("");return!0}validDecimal(a){let b=
parseFloat(a);return""!=a&&!isNaN(a)&&b>this.sqlDecMin&&b<this.sqlDecMax}isValidInt(a){var b=$(a);a=b.find(".form-control");let c=a.attr("max");b=b.find(".invalid-feedback");if(!this.validatePositiveInt(a.val(),c))return a.addClass("is-invalid"),b.text("Please enter a posivite integer whose value is at most "+c+"."),$("html, body").scrollTop(a.closest(".row").offset().top),!1;a.removeClass("is-invalid");b.text("");return!0}validatePositiveInt(a,b){let c=parseFloat(a),d=parseInt(a);return""!=a&&!isNaN(a)&&
0<d&&d<=b&&c==d}}var currentImageValues=new JuliaSetParams,juliaSetConstraints=new JuliaSetConstraints("{}");$(document).ready(function(){getConstraints();$("#generateJuliaSet").on("click",function(){generateImage()});$(".mainNavLink").on("keypress",function(a){13==a.keyCode&&this.click()});$("#skipNav").on("click",function(a){skipNav(this,a)});$(".juliaParam").on("change",function(){validateJuliaParam(this)})});function skipNav(a,b){a=$(a).attr("href");$(a).focus();b.stopPropagation()}
function getConstraints(){$.ajax({url:getContextPath()+"/getConstraints",type:"GET",success:function(a){juliaSetConstraints=new JuliaSetConstraints(a);generateImage()},error:function(a){console.log("error");console.log(a.responseText)}})}
function generateImage(){let a=new JuliaSetParams;validateImageGeneration(a)&&$.ajax({url:getContextPath()+"/generateJuliaSet.html",type:"GET",contentType:"application/json",data:a,success:function(b){$("#juliaSetPictureContainer").html(b);currentImageValues=a},error:function(b){console.log("error");console.log(b.responseText)}})}function validateImageGeneration(a){return!a.equals(currentImageValues)&&allParamsValid()}
function allParamsValid(){let a=!0;$(".juliaParam").each(function(){a=a&&validateJuliaParam(this)});return a}function validateJuliaParam(a){let b=$(a).attr("data-js-type");return"dec"==b?juliaSetConstraints.isValidDecimal(a):"int"==b?juliaSetConstraints.isValidInt(a):!0}function getContextPath(){return contextPath};
